[build]
  command = "yarn run react-build-once"
  publish = "dist-web"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit --no-fund"
  NODE_OPTIONS = "--max-old-space-size=4096"

# Increase memory limit for build
[build.processing]
  skip_processing = false 