[build]
  command = "yarn run react-build-once"
  publish = "dist-web"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit --no-fund"

# Increase memory limit for build
[build.processing]
  skip_processing = false

# Set max node memory for build process
[build.environment.NODE_OPTIONS]
  value = "--max-old-space-size=4096" 