[build]
  command = "yarn install && node build.js"
  publish = "dist-web"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit --no-fund"
  # Use fewer workers and disable caching to improve stability
  PARCEL_WORKERS = "1"
  NETLIFY_USE_YARN = "true"

# Increase memory limit for build
[build.processing]
  skip_processing = true 